server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /data/ {
        add_header Cache-Control "no-store";
    }

    location /live/ {
        proxy_pass http://api:8090/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Cache-Control "no-store";
    }

    location /img/image.coolapk.com/ {
        proxy_ssl_server_name on;
        proxy_set_header Host image.coolapk.com;
        proxy_set_header Referer "https://www.coolapk.com/";
        proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";
        proxy_pass https://image.coolapk.com/;
        add_header Cache-Control "public, max-age=86400";
    }

    location /img/avatar.coolapk.com/ {
        proxy_ssl_server_name on;
        proxy_set_header Host avatar.coolapk.com;
        proxy_set_header Referer "https://www.coolapk.com/";
        proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";
        proxy_pass https://avatar.coolapk.com/;
        add_header Cache-Control "public, max-age=86400";
    }
}
